query hello {
  hello
}

mutation {
  login(usernameOrEmail: "cstroman@gmail.com", password: "testDome12!") {
    errors {
      field
      message
    }
    user {
      id
      email
      first_name
      last_name
    }
  }
}

query {
  me {
    id
    username
  }
}

query GetChatRooms {
  chatRooms {
    id
    name
  }
}

mutation CreateChatRoom {
  createChatRoom(name: "Test Chat Room", user_id: 1) {
    id
    name
    createdAt
    user_id
  }
}

mutation SendChatMessage {
  sendMessage(
    input: { roomId: 1, username: "M", text: "Testing the chat subscription, test 1", user_id: 1 }
  ) {
    id
    roomId
    username
    text
    createdAt
    user_id
  }
}

subscription WatchChatMessages {
  messageSent(roomId: 1) {
    id
    roomId
    username
    text
    createdAt
  }
}
